#!/bin/sh
clear
#colour
R='\033[1;31m'
B='\033[0;34m'
C='\033[0;36m'
G='\033[1;32m'
W='\033[1;37m'
Y='\033[0;33m'
Y2='\033[1;33m'


#code
clear
echo " "
echo $G"  ██ ███    ██ ███████  █████ "
echo $G"  ██ ████   ██ ██      ██  ████"
echo $G"  ██ ██ ██  ██ █████   ██ ██ ██"
echo $G"  ██ ██  ██ ██ ██      ████  ██"
echo $G"  ██ ██   ████ ██$R Termux $G█████ Gathering by dave"
echo $Y2
echo  "------------------(main menu)-------------------"
echo
echo $B"[$R"01"$B]$G Inf0ga-----------> em@il ghather "
echo $B"[$R"02"$B]$G Cms detection----> CMS detection"
echo $B"[$R"00"$B]$G BACK "  
echo $B"[$W"XX"$B]$G EXIT "
echo " "
echo -n $R"[$W"Inf0rmation Gathering t00ls"$R]$W"~"$R"'#': 
read zaki
#Inf0ga
if [ $zaki = "1" ] || [ $zaki = "01" ];
then
clear
figlet -f small "           INF0GA"
echo $C "Exemple $R[$W google.com$R ] "
echo -n $R "Target or website$Y : " 
read site
python2 $PREFIX/share/EasY_HaCk/modules/Infoga/infoga.py --target $site --source all 
echo -n $R"Press" ENTRE to back" " 
read ENTRE
$PREFIX/share/EasY_HaCk/modules/inf0
#Cms detection
elif [ $zaki = "2" ] || [ $zaki = "02" ];
then 
echo
clear
python3 $PREFIX/share/EasY_HaCk/modules/CMSeeK/cmseek.py
echo -n  $R"Press" ENTRE to back" "
read ENTRE 
$PREFIX/share/EasY_HaCk/modules/inf0
#Back 
elif [ $zaki = "00" ] || [ $zaki = "0" ];
then
clear
echo "EasY_HacK "
sleep 1
clear
$PREFIX/share/EasY_HaCk/modules/web
elif [ $zaki = "X" ] || [ $zaki = "x" ] || [ $zaki = "xx" ] || [ $zaki = "XX" ] ;
then
clear
echo "by by (0_0)"
sleep 1
exit 
else
clear
echo $Y" Wrong Input..."
sleep 1
sh $0
fi
#end

