#!/bin/sh
clear
#colour
R='\033[1;31m'
B='\033[0;34m'
C='\033[0;36m'
G='\033[1;32m'
W='\033[1;37m'
Y='\033[0;33m'
Y2='\033[1;33m'

#variables
dir=/data/data/com.termux/files/home
kali=/data/data/com.termux/files/home/kali-fs
kali2=/data/data/com.termux/files/home/kali-arm64
kali3=/data/data/com.termux/files/home/kali-armhf
ubu=/data/data/com.termux/files/home/ubuntu-*
AIR=/data/data/com.termux/files/usr/bin/aircrack-ng
E=/data/data/com.termux/files/usr/share/EasY_HaCk/modules

clear
echo
echo $R"       ████████╗   ██████   ██████    ██     "
echo $B"       ╚══██╔══╝  ██    ██ ██    ██   ██     "
echo $C"          ██║     ██    ██ ██    ██   ██      "
echo $Y"          ██║     ██    ██ ██    ██   ██     "
echo $W"          ██║      ██████   ██████    ███████ $R v1"
echo "          ╚═╝                     "
echo $R"[$G"01"$R]$C"-"$R["$W"Osif$R]"
echo $R"[$G"02"$R]$C"-"$R["$W"Wascan$R]"
echo $R"[$G"03"$R]$C"-"$R["$W"Termux$C"-"$W"Theme"$R]"
echo $R"[$G"04"$R]$C"-"$R["$W"Tmux$C"-"$W"Bunch"$C"-"$W"v2.4"$R]"
echo $R"[$G"05"$R]$C"-"$R["$W"Setoolkit$R]"
echo $R"[$G"06"$R]$C"-"$R["$W"Spammer$C"-"$W"grab"$R]" 
echo $R"[$G"07"$R]$C"-"$R["$W"Socialfish$R]"
echo $R"[$G"08"$R]$C"-"$R["$W"Instahack$R]"
echo $R"[$G"BB"$R]$B"-"$R["$W"BaCk$R]"
echo "               "
echo -n $W"EasY_HaCk:~$R"#" " 
#osif
if [ "$zaki" = "1" ] || [ "$zaki" = "01" ];
then
clear
           if [ -d $dir/OSIF ];
				then
				echo
					echo "         $R"Y"$W"ou "$R"H"$W"ave "$R"O"$W"sif" "
					echo
					echo -n $R" Press" ENTRE to back" " 
					read ENTRE
					$PREFIX/share/EasY_HaCk/modules/Termux_Tools
			fi

cd $dir
git clone https://github.com/davekgw/osiff
cd OSIF
pip2 install -r requirements.txt > /dev/null;
echo -n $R" Press" ENTRE to back" " 
read ENTRE
$PREFIX/share/EasY_HaCk/modules/Termux_Tools
#Spammer-Grab
elif [ "$zaki" = "6" ] || [ "$zaki" = "06" ];
then
clear
			if [ -d $dir/Spammer-Grab ];
				then
				echo
					echo "         $R"Y"$W"ou "$R"H"$W"ave "$R"S"$W"pammer"$G"-"$R"G"$W"rab" "
					echo
					echo -n $R" Press" ENTRE to back" " 
					read ENTRE
					$PREFIX/share/EasY_HaCk/modules/Termux_Tools
			fi
cd $dir
git clone https://github.com/profionaldhim/Spammer-Grab && cd Spammer-Grab && unzip Spammer-Grab.zip && rm -rf Spammer-Grab.zip && mv Spammer-Grab spammer-grab && mv spammer-grab $dir && cd && rm -rf Spammer-Grab && mv spammer-grab Spammer-Grab && chmod 700 $dir/Spammer-Grab/* 
pip2 install requests > /dev/null;
echo "Done"
echo -n $R" Press" ENTRE to back" " 
read ENTRE
$PREFIX/share/EasY_HaCk/modules/Termux_Tools
#socialfish
elif [ "$zaki" = "7" ] || [ "$zaki" = "07" ];
then
clear
			if [ -d $dir/SocialFish ];
				then
				echo
					echo "         $R"Y"$W"ou "$R"H"$W"ave "$R"S"$W"ocialFish" "
					echo
					echo -n $R" Press" ENTRE to back" " 
					read ENTRE
					$PREFIX/share/EasY_HaCk/modules/Termux_Tools
			fi
cd $dir
git clone https://github.com/UndeadSec/SocialFish && cd SocialFish
pip install -r requirements.txt > /dev/null;
echo -n $R" Press" ENTRE to back" " 
read ENTRE
$PREFIX/share/EasY_HaCk/modules/Termux_Tools
#Tmux
elif [ "$zaki" = "4" ] || [ "$zaki" = "04" ];
then
clear
           if [ -d $dir/Tmux-Bunch ];
				then
				echo
					echo "         $R"Y"$W"ou "$R"H"$W"ave "$R"T"$W"mux"$G"-"$R"B"$W"unch" "
					echo
					echo -n $R" Press" ENTRE to back" " 
					read ENTRE
					$PREFIX/share/EasY_HaCk/modules/Termux_Tools
			fi

cd $dir
git clone https://github.com/sabri-zaki/Tmux-Bunch && cd Tmux-Bunch && chmod +x * && bash setup
echo -n $R" Press" ENTRE to back" " 
read ENTRE
$PREFIX/share/EasY_HaCk/modules/Termux_Tools
#wascan
elif [ "$zaki" = "2" ] || [ "$zaki" = "02" ];
then
clear
           if [ -d $dir/wascan ];
				then
				echo
					echo "         $R"Y"$W"ou "$R"H"$W"ave "$R"W"$W"ascan" "
					echo
					echo -n $R" Press" ENTRE to back" " 
					read ENTRE
					$PREFIX/share/EasY_HaCk/modules/Termux_Tools
			fi

cd $dir
git clone https://github.com/m4ll0k/WAScan.git wascan && cd wascan && chmod +x *
pip2 install BeautifulSoup > /dev/null;
echo -n $R" Press" ENTRE to back" " 
read ENTRE
$PREFIX/share/EasY_HaCk/modules/Termux_Tools
#setoolkit
elif [ "$zaki" = "5" ] || [ "$zaki" = "05" ];
then
clear
           if [ -d $dir/setoolkit ];
				then
				echo
					echo "         $R"Y"$W"ou "$R"H"$W"ave "$R"S"$W"etoolkit" "
					echo
					echo -n $R" Press" ENTRE to back" " 
					read ENTRE
					$PREFIX/share/EasY_HaCk/modules/Termux_Tools
			fi
			if [ -d $dir/setoolkit-for-termux ];
				then
				echo
					echo "         $R"Y"$W"ou "$R"H"$W"ave "$R"S"$W"etoolkit" "
					echo
					echo -n $R" Press" ENTRE to back" " 
					read ENTRE
					$PREFIX/share/EasY_HaCk/modules/Termux_Tools
			fi

cd $dir
apt update && apt upgrade
apt install python2 figlet python python-dev python2-dev wget tar termux-exec
wget https://hax4us.github.io/setoolkit_7.7.2.gz
tar -xf setoolkit_7.7.2.gz
cd setoolkit
pip install pexpect pycrypto pyopenssl pefile
python setup.py install 
echo
cd $dir
rm setoolkit_7.7.2.gz
clear
figlet Installed
echo -n $R" Press" ENTRE to back" " 
read ENTRE
$PREFIX/share/EasY_HaCk/modules/Termux_Tools
#Logo
elif [ "$zaki" = "03" ] || [ "$zaki" = "3" ];
then
clear
           if [ -e $PREFIX/bin/lolcat ];
				then
				 cd $dir
                 rm -rf $dir/.Log
                 wget https://raw.githubusercontent.com/davekgw/Log/master/logo                 clear
                 cd
                 read -p " Put Your Name Logo : " logo
                 sed "s/zaki/$logo/" $dir/logo > $dir/.Log
                 figlet -f big "   $logo" | lolcat
                 echo " Done"
                 rm -rf $dir/logo
                 sleep 2
	             $PREFIX/share/EasY_HaCk/modules/Termux_Tools
			fi
cd $dir
gem install lolcat
rm -rf $dir/.Log
wget https://raw.githubusercontent.com/davekgw/Log/master/logo
clear
cd
#read logo
read -p " Put Your Name Logo : " logo
sed "s/zaki/$logo/g" $dir/logo > $dir/.Log
figlet -f big "   $logo" | lolcat
echo " Done"
rm -rf $dir/logo
sleep 1
$PREFIX/share/EasY_HaCk/modules/Termux_Tools
#instahack
elif [ "$zaki" = "8" ] || [ "$zaki" = "08" ];
then
clear
           if [ -e $dir/instahack ];
				then
				echo
					echo "         $R"Y"$W"ou "$R"H"$W"ave "$R"I"$W"nstahack" "
					echo
					echo -n $R" Press" ENTRE to back" " 
					read ENTRE
					$PREFIX/share/EasY_HaCk/modules/Termux_Tools
			fi
cd $dir
git clone https://github.com/fuck3erboy/instahack
echo -n $R" Press" ENTRE to back" " 
read ENTRE
$PREFIX/share/EasY_HaCk/modules/Termux_Tools
#loop-back
elif [ $zaki == ]; 
then
clear
$PREFIX/share/EasY_HaCk/modules/Termux_Tools
fi
#back
if [ "$zaki" = "B" ] || [ "$zaki" = "BB" ] || [ "$zaki" = "b" ] || [ "$zaki" = "bb" ];
then
EasY_HaCk
fi
